# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/7.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

    email:
        enabled: true
        digits: 8
        mailer: 'App\Service\MailerService'
        sender_email: '%env(TWOFACTOR_FROM_ADDRESS_EMAIL)%'
        sender_name: '%env(TWOFACTOR_FROM_ADDRESS_NAME)%'

    google:
        enabled: true
        server_name: NSS
        digits: 6
